["lab.api"]
master = "PC03"
master_hostname="ns"
ip_master = "10.0.1.2"
slaves = ["PC04"]
ip_slaves = ["10.0.1.3"]
iprange = "10.0.1.0"
dirfile = "lab.db"
invfile = "lab_inv.db"
admin = "admin"
mask = 27
ttl = 64000
serial = 2018111201

[["lab.api".RR]]
type = "NS"
name = "ns"
ip = "10.0.1.2"
[["lab.api".RR]]
type = "NS"
name = "ns2"
ip = "10.0.1.3"
[["lab.api".RR]]
type = "MX"
name = "mail"
ip = "10.0.1.4"
priority = 10
[["lab.api".RR]]
type = "A"
name = "www"
ip = "10.0.1.5"
[["lab.api".RR]]
type = "A"
name = "usr1"
ip = "10.0.1.66"
[["lab.api".RR]]
type = "A"
name = "usr2"
ip = "10.0.1.98"

[["lab.api".subdomain]]
dns_name = "ns"
subdomain = "subgrup"
dns_ip = "10.0.1.130"
iprange = "10.0.1.128"
mask = 25
ips = ["10.0.1.130", "10.0.1.131", "10.0.1.162"]