#!/bin/bash

lxc-attach -n R03 -- ip tunnel add tun6to4 mode sit ttl 64 remote any local 1.1.3.3
lxc-attach -n R03 -- ip link set dev tun6to4 up
lxc-attach -n R03 -- ip -6 route add ::/0 dev tun6to4
lxc-attach -n R05 -- ip tunnel add tun6to4 mode sit ttl 64 remote any local 1.1.5.5
lxc-attach -n R05 -- ip link set dev tun6to4 up
lxc-attach -n R05 -- ip -6 route add ::/0 dev tun6to4

