#!/bin/bash
count_dirs () {
    dir=$1   
    regexp=$2
    wc -l < <( awk '{print $NF}' < <(ls -l $dir) | grep -P $regexp )
}
if [[ ("$#" -eq 0 ) || ("$#" -eq 1 && $1 == "all") ]]; then
routers=$(count_dirs "/var/lib/lxc/" "^R[0-9]{2}$")
pcs=$(count_dirs "/var/lib/lxc/" "^PC[0-9]{2}$")
05-stop-containers $routers $pcs
06-clean-quagga-files $routers
if [ "$#" -eq 0 ]; then
     02-copy-files 10 /home/api/practiques/P01/P01-E02/config_files_$(printf "PC%d" 1)
elif [ "$#" -eq 1 ]; then
     02-copy-files 10 /home/api/practiques/P01/P01-E02-backup/config_files_$(printf "PC%d" 1)
fi
03-create-bridges 19
04-start-containers 10
04-rp-filter 10
lxc-attach -n R01 -- ip route add 0.0.0.0/0 via 10.0.0.226
lxc-attach -n R05 -- ip route add 10.0.0.0/25 via 10.0.0.113
lxc-attach -n R05 -- ip route add 10.0.0.128/25 via 10.0.0.241
lxc-attach -n R03 -- ip route add 10.0.0.0/25 via 10.0.0.98
lxc-attach -n R03 -- ip route add 10.0.0.128/25 via 10.0.0.249
lxc-attach -n R03 -- ip route add 10.0.0.120/29 via 10.0.0.114
lxc-attach -n R04 -- ip route add 0.0.0.0/0 via 10.0.0.97
lxc-attach -n R02 -- ip route add 10.0.0.0/25 via 10.0.0.250
lxc-attach -n R02 -- ip route add 10.0.0.128/25 via 10.0.0.225
lxc-attach -n R02 -- ip route add 10.0.0.120/29 via 10.0.0.242
echo "Done!"
else
     echo "error a l'introduir els paràmetres"
fi

