#!/bin/bash
num_routers=12
num_bridges=19
folder=P02/P02-E01

if [[ ("$#" -eq 0 ) || ("$#" -eq 1 && $1 == "all") ]]; then
if [ "$#" -eq 0 ]; then
     02-copy-files $num_routers /home/api/practiques/$folder/config_files_zebra_$(printf "PC%d" 1) r
elif [ "$#" -eq 1 ]; then
     02-copy-files $num_routers /home/api/practiques/$folder-backup/config_files_zebra_$(printf "PC%d" 1) r
fi
sysctl -w fs.inotify.max_user_instances=1024
for ((i=1; i<=$num_routers; i++))
    do lxc-attach -n $(printf "R%02d" $i) -- systemctl start ripd
       echo Starting ripd in $(printf "R%02d" $i) .............
done
echo "Done!"
else
     echo "error a l'introduir els paràmetres"
fi


