#!/bin/bash
num_routers=15
num_pcs=9
num_bridges=36
folder=P02/P02-E02

count_dirs () {
    dir=$1   
    regexp=$2
    wc -l < <( awk '{print $NF}' < <(ls -l $dir) | grep -P $regexp )
}

if [[ ("$#" -eq 0 ) || ("$#" -eq 1 && $1 == "all") ]]; then
routers=$(count_dirs "/var/lib/lxc/" "^R[0-9]{2}$")
pcs=$(count_dirs "/var/lib/lxc/" "^PC[0-9]{2}$")
05-stop-containers $routers $pcs
06-clean-quagga-files $routers
if [ "$#" -eq 0 ]; then
     02-copy-files $num_routers /home/api/practiques/$folder/config_files_zebra_$(printf "PC%d" 1) z
     02-copy-files-PCs $num_pcs /home/api/practiques/$folder/config_files_zebra_$(printf "PC%d" 1) z
elif [ "$#" -eq 1 ]; then
     02-copy-files $num_routers /home/api/practiques/$folder-backup/config_files_zebra_$(printf "PC%d" 1) z
     02-copy-files-PCs $num_pcs /home/api/practiques/$folder/config_files_zebra_$(printf "PC%d" 1) z
fi
03-create-bridges $num_bridges
04-start-containers $num_routers $num_pcs
04-rp-filter $num_routers $num_pcs
echo "Done!"
else
     echo "error a l'introduir els paràmetres"
fi

