#!/bin/bash
num_routers=15
num_pcs=7
num_bridges=33
folder=P03/P03-E02

if [[ ("$#" -eq 0 ) || ("$#" -eq 1 && $1 == "all") ]]; then
if [ "$#" -eq 0 ]; then
     02-copy-files $num_routers /home/api/practiques/$folder/config_files_zebra_$(printf "PC%d" 1) o
     02-copy-files-PCs $num_pcs /home/api/practiques/$folder/config_files_zebra_$(printf "PC%d" 1) o
elif [ "$#" -eq 1 ]; then
     02-copy-files $num_routers /home/api/practiques/$folder-backup/config_files_zebra_$(printf "PC%d" 1) o
     02-copy-files-PCs $num_pcs /home/api/practiques/$folder-backup/config_files_zebra_$(printf "PC%d" 1) o
fi
sysctl -w fs.inotify.max_user_instances=1024
for ((i=1; i<=$num_routers; i++))
    do lxc-attach -n $(printf "R%02d" $i) -- systemctl start ospfd
       echo Starting ospfd in $(printf "R%02d" $i) .............
done
for ((i=1; i<=$num_pcs; i++))
    do lxc-attach -n $(printf "PC%02d" $i) -- systemctl start ospfd
       echo Starting ospfd in $(printf "PC%02d" $i) .............
done
echo "Done!"
else
     echo "error a l'introduir els paràmetres"
fi


