#!/bin/bash
total=$1
for ((i=1; i<=$total; i++))
    do cp $2/config_$(printf "PC%02d" $i) /var/lib/lxc/$(printf "PC%02d" $i)/config
done

if [ "$#" -eq 3 ]; then
	if [[ $3 == z ]]; then 
		for ((i=1; i<=$total; i++)); do
			if [ -f $2/zebra.conf_$(printf "PC%02d" $i) ]; then
				cp $2/zebra.conf_$(printf "PC%02d" $i) /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/etc/quagga/zebra.conf
			fi
		done
	fi
        if [[ $3 == r ]]; then 
                for ((i=1; i<=$total; i++)); do
			if [ -f $2/ripd.conf_$(printf "PC%02d" $i) ]; then
                        	cp $2/ripd.conf_$(printf "PC%02d" $i) /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/etc/quagga/ripd.conf
			fi
                done
        fi
        if [[ $3 == o ]]; then 
                for ((i=1; i<=$total; i++)); do 
			if [ -f $2/ospfd.conf_$(printf "PC%02d" $i) ]; then
	                        cp $2/ospfd.conf_$(printf "PC%02d" $i) /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/etc/quagga/ospfd.conf
			fi
                done
        fi
fi

