#!/bin/bash
total=$1
for ((i = 1; i <= $total; i++)); do
	lxc-copy -n api -N $(printf "R%02d" $i)
done
if [ "$#" -eq 2 ]; then
	total=$2
	for ((i = 1; i <= $total; i++)); do
		lxc-copy -n api -N $(printf "PC%02d" $i)
	done
fi
