#!/bin/bash
total=$1
for ((i = 1; i <= $total; i++)); do
	cp $2/config_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/config
done

if [ "$#" -eq 3 ]; then
	if [[ $3 == z ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/zebra.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/zebra.conf
		done
	fi
	if [[ $3 == r ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/ripd.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/ripd.conf
		done
	fi
	if [[ $3 == o ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/ospfd.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/ospfd.conf
		done
	fi
	if [[ $3 == b ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/bgpd.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/bgpd.conf
		done
	fi
	if [[ $3 == zr ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/zebra.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/zebra.conf
			cp $2/ripd.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/ripd.conf
		done
	fi
	if [[ $3 == zo ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/zebra.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/zebra.conf
			cp $2/ospfd.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/ospfd.conf
		done
	fi
	if [[ $3 == zb ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/zebra.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/zebra.conf
			cp $2/bgpd.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/bgpd.conf
		done
	fi
	if [[ $3 == zob ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/zebra.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/zebra.conf
			cp $2/ospfd.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/ospfd.conf
			cp $2/bgpd.conf_$(printf "R%02d" $i) /var/lib/lxc/$(printf "R%02d" $i)/rootfs/etc/quagga/bgpd.conf
		done
	fi
fi
