#!/bin/bash
total=$1
for ((i = 1; i <= $total; i++)); do
	cp $2/config_$(printf "PC%02d" $i) /var/lib/lxc/$(printf "PC%02d" $i)/config
	cp $2/f*_$(printf "PC%02d" $i) /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/home/api
	chmod 755 /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/home/api/f*_$(printf "PC%02d" $i)
done

if [ "$#" -eq 3 ]; then
	if [[ $3 == z ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/zebra.conf_$(printf "PC%02d" $i) /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/etc/quagga/zebra.conf
		done
	fi
fi
