#!/bin/bash
total=$1
for ((i = 1; i <= $total; i++)); do
	cp $2/config_$(printf "PC%02d" $i) /var/lib/lxc/$(printf "PC%02d" $i)/config
done

if [ "$#" -eq 3 ]; then
	if [[ $3 == z ]]; then
		for ((i = 1; i <= $total; i++)); do
			cp $2/zebra.conf_$(printf "PC%02d" $i) /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/etc/quagga/zebra.conf
		done
	fi
fi
