#!/bin/bash
total=$1
for ((i = 1; i <= $total; i++)); do
	lxc-attach -n $(printf "R%02d" $i) -- bash -c "echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter"
	lxc-attach -n $(printf "R%02d" $i) -- bash -c "echo 0 > /proc/sys/net/ipv4/conf/default/rp_filter"
done
if [ "$#" -eq 2 ]; then
	total=$2
	for ((i = 1; i <= $total; i++)); do
		lxc-attach -n $(printf "PC%02d" $i) -- bash -c "echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter"
		lxc-attach -n $(printf "PC%02d" $i) -- bash -c "echo 0 > /proc/sys/net/ipv4/conf/default/rp_filter"
	done
fi
