#!/bin/bash
total=$1
for ((i = 1; i <= $total; i++)); do
	rm /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/etc/quagga/*.conf
	cp /var/lib/lxc/api/rootfs/etc/quagga/zebra.conf /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/etc/quagga/zebra.conf
	touch /var/lib/lxc/$(printf "PC%02d" $i)/rootfs/etc/quagga/vtysh.conf
done
