#!/bin/bash
pkg="jq"
if dpkg --get-selections | grep -q "^$pkg[[:space:]]*install$" > /dev/null; then
	echo -e "$pkg is already installed"
else
	if apt-get -qq install $pkg; then
	   	echo "$pkg successfully installed "
	else
		echo "Error installing $pkg"
		exit
	fi
fi

# Command line parameters parsing
if [ -z "$1" ] ; then
    echo "Usage: ./install-api-labs labs.tar.gz"
    exit
fi
labs_tgz=$1
if [ ! -f ${lab_tgz} ]; then
    echo "${labs_tgz} not found"
    exit
fi

# Descomprime en un directorio temporal
mkdir -p /tmp/api/
#rm -fr /tmp/api/*
tar -zxf ${labs_tgz} -C /tmp/api

rm -fr /opt/api
cp -r /tmp/api /opt
chmod u+x /opt/api/labs/scripts/{install-scenario,launch-scenario,save-scenario,stop-scenario}
rm -fr /tmp/api

rm -f /usr/local/bin/install-scenario
rm -f /usr/local/bin/launch-scenario
rm -f /usr/local/bin/save-scenario
rm -f /usr/local/bin/stop-scenario

ln -s /opt/api/labs/scripts/install-scenario /usr/local/bin/install-scenario
ln -s /opt/api/labs/scripts/launch-scenario /usr/local/bin/launch-scenario
ln -s /opt/api/labs/scripts/save-scenario /usr/local/bin/save-scenario
ln -s /opt/api/labs/scripts/stop-scenario /usr/local/bin/stop-scenario

for ((i=1; i<=15; i++)) ; do
  router=$(printf "R%02d" "$i")
  if [ ! -z "$( lxc-ls -f | grep $router )" ] ;then
    ln -sfn /lib/systemd/system/ripd.service /var/lib/lxc/$router/rootfs/etc/systemd/system/multi-user.target.wants/ripd.service
    ln -sfn /lib/systemd/system/ospfd.service /var/lib/lxc/$router/rootfs/etc/systemd/system/multi-user.target.wants/ospfd.service
    ln -sfn /lib/systemd/system/bgpd.service /var/lib/lxc/$router/rootfs/etc/systemd/system/multi-user.target.wants/bgpd.service
  fi
done

echo ""
echo "api-labs successfully installed "
